server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/cloud-order?useSSL=false
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
#    password: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice #order服务名称
  cloud:
    nacos:
#      server-addr: localhost:8848
      server-addr: nacos:8848
      discovery:
#        cluster-name: HZ # 集群名称
        namespace: 743c953d-a699-45ab-a680-79159fe87ad0 # dev环境
        ephemeral: false # 修改为非临时实例，临时实例向nacos发送心跳，nacos未检测到时会自动删除，非临时实例nacos向service发送心跳，不会被剔除
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: # eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

# 该服务对userservice的特定负载均衡策略
# feign集成了Ribbon，实现了轮换负载均衡
userservice:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 随机负载均衡
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # nacos的集群负载均衡策略，本集群挂掉会访问其他集群并爆出警告


#默认懒加载，现在开启饥饿加载，启动时就会载入负载的列表，第一次调用会更快
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: #指定对哪些服务饥饿加载
      - userservice

# feign使用配置文件设置日志级别NONE-无（默认），BASIC-发起结束时间等,HEADERS-基本+请求头响应头,FULL-所有
feign:
  client:
    config:
      default: #针对全局
        loggerLevel: BASIC
#      userservice: #针对特定服务
#        loggerLevel: HEADERS
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数